version: "3.9"

services:
  # ──────────────── Flask + Gunicorn ────────────────
  backend:
    build:
      context: ./Backend
    env_file:
      - ./Backend/.env          # AISSTREAM_API_KEY, etc.
    
    command: >
      gunicorn flaskr:app -b 0.0.0.0:5000 -w 3

    volumes:
      - db-data:/app/instance   # keep SQLite db between restarts
    ports:
      - "8000:5000"            # host:container
    expose:
      - "5000"                 # container:container

  # ──────────────── Vite‑built SPA served by Nginx ────────────────
  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:80"               # host:container
    depends_on:
      - backend

volumes:
  db-data:
